name: Flutter CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Create .env file
        run: cp .env.example .env

      - name: Create firebase_options.dart
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
        run: |
          python3 -c "import os; open('lib/firebase_options.dart', 'w').write(os.environ['FIREBASE_OPTIONS'])"
          dart format lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run static analysis
        run: flutter analyze

    #   - name: Run tests
    #     run: flutter test